model:
  name: tree_boosting
  label: XGBoost V1
  version: "v1"
  run_id: xgboost_v1

parameters:
  estimator: xgboost

  n_estimators: 80
  max_depth: 2
  learning_rate: 0.01
  subsample: 0.8
  colsample_bytree: 0.8

  reg_alpha: 0.05
  reg_lambda: 0.035

  min_child_weight: 5

  random_state: 42
  n_jobs: -1

  minimum_training_weeks: 104

features:
  feature_set: weekly_v1
  feature_map_path: data/processed/weekly_features_weekly_v1.csv

  selected_columns:
    - downside_deviation_4
    - risk_adjusted_mean_4
    - downside_deviation_12
    - risk_adjusted_mean_12
    - momentum_spread_4_12
    - excess_return_lag_1
    - excess_return_lag_2
    - excess_return_lag_4
    - excess_rolling_mean_4
    - excess_rolling_mean_12
    - return_lag_1_cs_z
    - return_lag_4_cs_z
    - return_lag_12_cs_z
    - rolling_mean_4_cs_z
    - rolling_mean_12_cs_z
    - rolling_mean_26_cs_z
    - risk_adjusted_mean_4_cs_z
    - excess_return_lag_1_cs_z