model:
  name: tree_boosting
  label: XGBoost SMIC V1   #<--- change this (show in the csv)
  version: "v1"             #<--- change this
  run_id: xgboost_SMIC_v1  #<--- change this (same as file name)

parameters:
  estimator: xgboost
  random_state: 42
  n_jobs: -1
  n_estimators: 40
  max_depth: 4
  learning_rate: 0.02791645976159515
  subsample: 0.8275218865889229
  colsample_bytree: 0.6020759965478057
  reg_alpha: 0.0015126508378582567
  reg_lambda: 0.005762230801753824
  min_child_weight: 6
  minimum_training_weeks: 104
training:
  tickers:
  - 0981.HK
  - 0700.HK
  - 1810.HK
  - 9988.HK
  - 3988.HK
  - 1398.HK
features:
  feature_set: weekly_v1
  feature_map_path: data/processed/weekly_features_weekly_v1.csv
  selected_columns:
  - return_lag_2
  - return_lag_3
  - return_lag_24
  - return_lag_52
  - downside_deviation_4
  - risk_adjusted_mean_4
  - rolling_mean_12
  - rolling_std_12
  - downside_deviation_12
  - rolling_std_26
  - market_rolling_mean_12
  - market_rolling_mean_26
  - excess_return_lag_4
  - excess_return_lag_8
  - excess_return_lag_12
  - excess_rolling_mean_12
  - return_lag_1_cs_z
  - rolling_mean_4_cs_z
  - rolling_mean_26_cs_z
