from __future__ import annotations

from typing import Any

import pandas as pd
from sklearn.linear_model import ElasticNet, Lasso, Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from src.hk_equity.features.weekly_features import (
    WeeklyFeatureSpec,
    build_live_features,
    build_weekly_training_features,
    drop_incomplete_feature_rows,
    get_feature_columns,
)


def build_feature_spec(
    parameters: dict[str, Any],
) -> WeeklyFeatureSpec:
    """Build a feature specification from model parameters."""

    feature_set = parameters.get(
        "feature_set",
        "weekly_v1",
    )

    if feature_set != "weekly_v1":
        raise ValueError(
            f"Unknown feature_set '{feature_set}'. "
            "Available feature sets: weekly_v1"
        )

    return WeeklyFeatureSpec(
        include_ratio_features=parameters.get(
            "include_ratio_features",
            False,
        ),
        include_cross_sectional_features=parameters.get(
            "include_cross_sectional_features",
            True,
        ),
        winsorize_features=parameters.get(
            "winsorize_features",
            False,
        ),
        winsorize_lower=parameters.get(
            "winsorize_lower",
            0.05,
        ),
        winsorize_upper=parameters.get(
            "winsorize_upper",
            0.95,
        ),
    )


def build_regression_estimator(
    parameters: dict[str, Any],
) -> Pipeline:
    """Create a configurable scikit-learn regression pipeline."""

    estimator_name = parameters.get(
        "estimator",
        "ridge",
    ).lower()

    alpha = float(
        parameters.get("alpha", 1.0)
    )

    if alpha <= 0:
        raise ValueError(
            "alpha must be greater than zero."
        )

    polynomial_degree = int(
        parameters.get("polynomial_degree", 1)
    )

    if polynomial_degree < 1:
        raise ValueError(
            "polynomial_degree must be at least 1."
        )

    fit_intercept = bool(
        parameters.get("fit_intercept", True)
    )

    max_iter = int(
        parameters.get("max_iter", 10000)
    )

    if estimator_name == "ridge":
        estimator = Ridge(
            alpha=alpha,
            fit_intercept=fit_intercept,
        )

    elif estimator_name == "lasso":
        estimator = Lasso(
            alpha=alpha,
            fit_intercept=fit_intercept,
            max_iter=max_iter,
        )

    elif estimator_name in {
        "elastic_net",
        "elasticnet",
    }:
        l1_ratio = float(
            parameters.get("l1_ratio", 0.5)
        )

        if not 0 <= l1_ratio <= 1:
            raise ValueError(
                "l1_ratio must be between 0 and 1."
            )

        estimator = ElasticNet(
            alpha=alpha,
            l1_ratio=l1_ratio,
            fit_intercept=fit_intercept,
            max_iter=max_iter,
        )

    else:
        raise ValueError(
            f"Unknown regression estimator '{estimator_name}'. "
            "Available estimators: ridge, lasso, elastic_net"
        )

    steps = []

    if polynomial_degree > 1:
        steps.append(
            (
                "polynomial_features",
                PolynomialFeatures(
                    degree=polynomial_degree,
                    include_bias=False,
                ),
            )
        )

    if parameters.get("standardize", True):
        steps.append(
            (
                "standard_scaler",
                StandardScaler(),
            )
        )

    steps.append(
        (
            "regressor",
            estimator,
        )
    )

    return Pipeline(steps)


def _validate_predictions(
    predictions: pd.Series,
    tickers: list[str],
) -> pd.Series:
    """Validate and order one prediction per portfolio ticker."""

    predictions = predictions.reindex(tickers)

    if predictions.isna().any():
        missing_tickers = predictions[
            predictions.isna()
        ].index.tolist()

        raise ValueError(
            "Regression model produced missing predictions for: "
            f"{missing_tickers}"
        )

    return predictions.astype(float)


def get_regression_forecast(
    weekly_returns: pd.DataFrame,
    benchmark_returns: pd.Series,
    parameters: dict[str, Any],
) -> pd.Series:
    """Fit a regression model and forecast next-week returns.

    The model is trained on historical rows generated by
    ``build_weekly_training_features``. It then predicts one return for each
    ticker using the latest completed-week features from ``build_live_features``.
    """

    if benchmark_returns is None:
        raise ValueError(
            "benchmark_returns is required for regression forecasting."
        )

    feature_spec = build_feature_spec(parameters)

    training_features = build_weekly_training_features(
        weekly_returns=weekly_returns,
        benchmark_returns=benchmark_returns,
        spec=feature_spec,
    )

    feature_columns = get_feature_columns(
        training_features
    )

    clean_training_features = drop_incomplete_feature_rows(
        feature_table=training_features,
        feature_columns=feature_columns,
    )

    if clean_training_features.empty:
        raise ValueError(
            "No complete training rows are available for regression."
        )

    live_features = build_live_features(
        weekly_returns=weekly_returns,
        benchmark_returns=benchmark_returns,
        spec=feature_spec,
    )

    live_features = live_features.reindex(
        columns=["ticker", *feature_columns]
    )

    if live_features[feature_columns].isna().any().any():
        missing_feature_columns = live_features[
            feature_columns
        ].columns[
            live_features[feature_columns].isna().any()
        ].tolist()

        raise ValueError(
            "Live regression features contain missing values in: "
            f"{missing_feature_columns}"
        )

    model = build_regression_estimator(parameters)

    X_train = clean_training_features[feature_columns]
    y_train = clean_training_features["target"]
    X_live = live_features[feature_columns]

    model.fit(X_train, y_train)

    raw_predictions = model.predict(X_live)

    predictions = pd.Series(
        raw_predictions,
        index=live_features["ticker"],
        name="predicted_weekly_return",
    )

    return _validate_predictions(
        predictions=predictions,
        tickers=list(weekly_returns.columns),
    )